[phases.setup]
nixPkgs = ["nodejs_18", "python3", "python3Packages.pip"]

[phases.install]
cmds = [
  "python3 -m pip install -r requirements.txt",
  "cd frontend && npm ci"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "python3 main.py"
