[phases.setup]
nixPkgs = ["nodejs_18", "python311", "wget", "curl", "gcc", "pkg-config", "glibc", "libgcc"]

[phases.install]
cmds = [
  "curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python3 get-pip.py --break-system-packages",
  "python3 -m pip install --break-system-packages -r requirements.txt",
  "cd frontend && npm ci"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "LD_LIBRARY_PATH=/nix/store/*/lib:$LD_LIBRARY_PATH uvicorn app.main:app --host 0.0.0.0 --port $PORT"