[phases.setup]
nixPkgs = ["nodejs_18", "python311"]

[phases.install]
cmds = [
  "python3 -m pip install --break-system-packages -r requirements.txt",
  "cd frontend && npm ci"
]

[phases.build]
cmds = ["cd frontend && npm run build"]