[phases.setup]
nixPkgs = ["nodejs_18", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip install -r requirements.txt", 
  "cd frontend && npm ci"
]

[phases.build]
cmds = ["cd frontend && npm run build"]